name: build
on: push
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
        run: make
